### ISSUE TITLE
change config 

### ISSUE THREAD

**Issue by hannesdelbeke** [hannesdelbeke/buttonizer#5]
current config 
```YAML
- category: Print text
  command: print('Hello')
  name: Print Hello
- category: Print text
  command: print('Awesome')
  name: Print Awesome
- category: Math
  command: print(2*5)
  name: 2 x 5
```

possible new command. `commandname: command`
```YAML
- category: Print text
  Print Hello: print('Hello')
  Print Awesome: print('Awesome')
- category: Math
  2 x 5: command: print(2*5)
```
- any issues with dupe names? bad practice IMO so non issue
- any issues if name starts with a number?
- any other limitations?
